### ISSUE TITLE
Export PNG chart just show results for the past month

### ISSUE THREAD

**Issue by cuducos** [dizballanze/m00dbot#3]
Hi @dizballanze,

First of all, thanks for this awesome project : )

I noticed a bug I guess… when I do `/export` and choose CSV, I can get all results from June (past month, when I started using the bot) until today. However, if I do `/export` I get a chart that is limited to June results only (nothing from the current month).

I read the code, and I see that queries are different:

* For PNG the query is [`quiz_storage.get_completed_quizes(query.message.chat_id)`](https://github.com/dizballanze/m00dbot/blob/master/bot.py#L146)
* For CSV it is [`quiz_storage.get_completed_quizes(query.message.chat_id, limit=999)`](https://github.com/dizballanze/m00dbot/blob/master/bot.py#L150)

I think that as [the default for `get_completed_quizes` is 10, and there's no ordering](https://github.com/dizballanze/m00dbot/blob/master/storage.py#L31-L46), the PNG export will always show my first 10 results.

What about raising the default limit to 30 (roughly a full month) and ordering by `DESC` to always get the _last_ results instead of the first ones? Does it sound like a fix?

**Comment by dizballanze** [comment]
Hi @cuducos. Thanks for the report. I will try to check this out on the weekend.
If you could provide a Pull Request, it would be faster.

**Comment by cuducos** [comment]
> If you could provide a Pull Request, it would be faster.

Drafting something in #4, let me know what you think about it and we can better discuss the issue over there : )

**Comment by cuducos** [comment]
Fixed by #4
